export const MAINTENANCE_SET = 'maintenance/SET'
export const FORCEUPDATE_SET = 'forceupdate/SET'

export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const FETCH_FAILED = "FETCH_FAILED";
export const UN_AUTHORISED = "UN_AUTHORISED";
export const SHOW_LOADER = "SHOW_LOADER";
export const CURRENT_API = "CURRENT_API";

export const CURRENT_USER_TOKEN = "CURRENT_USER_TOKEN";
export const CURRENT_USER_ROLE = "CURRENT_USER_ROLE";
export const PROFILE_DATA = "PROFILE_DATA";
export const LAST_DAILY_LIST_PARAMS = "LAST_DAILY_LIST_PARAMS";

export const SET_SCAN_INFO = "SET_SCAN_INFO";
export const SET_NETWORK_INFO = 'SET_NETWORK_INFO';
export const SET_PERMISSION_INFO = 'SET_PERMISSION_INFO';
export const SET_STORED_BID = "SET_STORED_BID";
export const SET_BUSINESS_NAME = "SET_BUSINESS_NAME";
export const SET_STORED_CID = "SET_STORED_CID";
export const SET_CUSTOMER_NAME = "SET_CUSTOMER_NAME";

export const SET_REMEMBER_ME = "SET_REMEMBER_ME";
export const SET_FCM_TOKEN = "SET_FCM_TOKEN";


export const SET_CUSTOM_PARAMETERS= "SET_CUSTOM_PARAMETERS";

